const path = require('path');
const fs = require('fs');

// List of scripts to concatenate for MV3 service worker
// NOTE: Only include files that are safe for service worker context!
// Service workers have NO access to: document, window, DOM APIs
// Modules that run on Hattrick pages should ONLY be in content_scripts (manifest.json)
const scriptFiles = [
	// Essential core
	'content/env.js',
	'content/prefs-util.js',
	'content/l10n.js',
	'content/xml-load.js',
	'content/pages.js',

	// Essential libraries (NO indexedDB.polyfill.js - causes errors in service worker!)
	'content/lib/idbstore.js',
	'content/lib/oauth.js',
	'content/lib/sha1.js',
	'content/lib/PluralForm.js',
	'content/lib/yaml.js',
	'content/lib/integration.js',

	// Background-safe utilities only (NO DOM utilities!)
	'content/util/api.js',
	'content/util/array.js',
	'content/util/async.js',
	'content/util/color.js',
	'content/util/cookies.js',
	'content/util/css.js',
	'content/util/currency.js',
	'content/util/ht-ml.js',
	'content/util/id.js',
	'content/util/load.js',
	'content/util/local-store.js',
	'content/util/log.js',
	'content/util/match-event.js',
	'content/util/match-view.js',
	'content/util/math.js',
	'content/util/misc.js',
	'content/util/module.js',
	'content/util/notify.js',
	'content/util/permissions.js',
	'content/util/sanitize.js',
	'content/util/session-store.js',
	'content/util/string.js',
	'content/util/tabs.js',
	'content/util/time.js',

	// Core (minimal - only what background needs)
	'content/core.js',
	'content/ui.js',

	// Background initialization (from entry.js, service-worker safe functions only)
	'content/background-init.js',

	// Background script MUST be last
	'content/background.js',
];

// Custom plugin to concatenate all scripts
class ConcatenateScriptsPlugin {
	apply(compiler) {
		const webpack = compiler.webpack;
		const { Compilation } = webpack;
		const { RawSource } = webpack.sources;

		compiler.hooks.thisCompilation.tap('ConcatenateScriptsPlugin', (compilation) => {
			compilation.hooks.processAssets.tap(
				{
					name: 'ConcatenateScriptsPlugin',
					stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONAL,
				},
				() => {
					let concatenated = '';

					// Add header comment
					concatenated += '/**\n';
					concatenated += ' * Foxtrick MV3 Service Worker Bundle\n';
					concatenated += ' * Auto-generated by webpack - DO NOT EDIT\n';
					concatenated += ' */\n\n';
					concatenated += '"use strict";\n\n';

					for (const file of scriptFiles) {
						try {
							const content = fs.readFileSync(file, 'utf8');
							concatenated += `\n// ===== ${file} =====\n`;
							concatenated += content;
							concatenated += `\n// ===== END ${file} =====\n\n`;
						}
						catch (err) {
							console.error(`Error reading ${file}:`, err.message);
							compilation.errors.push(new Error(`Failed to read ${file}: ${err.message}`));
						}
					}

					// Add the bundle to compilation assets using modern API
					compilation.emitAsset('background-bundle.js', new RawSource(concatenated));
				}
			);
		});
	}
}

module.exports = {
	mode: 'production',
	entry: './content/background-entry.js',
	output: {
		filename: 'background-bundle-unused.js', // Won't be used, ConcatenateScriptsPlugin creates the real one
		path: path.resolve(__dirname, 'content'),
		clean: false,
		globalObject: 'self',
	},
	target: 'webworker',
	devtool: 'source-map',
	optimization: {
		minimize: false, // Don't minimize - we're just concatenating
	},
	plugins: [
		new ConcatenateScriptsPlugin(),
	],
	stats: {
		colors: true,
		modules: false,
		children: false,
		chunks: false,
		chunkModules: false,
	},
};
