pref( "extensions.foxtrick.prefs.curVersion", "0.4.8.2");   // update with each release
pref( "extensions.foxtrick.prefs.oldVersion", "0.3.73");   // don't change!! (unless you know what you do). shows changes form that version onwards after new installation
pref( "extensions.foxtrick.prefs.HTURL", "^http:\/\/(stage\.|www\d*\.|www\.new\.){0,1}hattrick\.(org|ws|interia\.pl)" );
pref( "extensions.foxtrick.prefs.htLanguage", "en");
pref( "extensions.foxtrick.prefs.module.FoxtrickReadHtPrefs.enabled",true );
pref( "extensions.foxtrick.prefs.htCurrency", "EUR");
pref( "extensions.foxtrick.prefs.currencyRateTo", "1.0");
pref( "extensions.foxtrick.prefs.currencyCode", "EUR");
pref( "extensions.foxtrick.prefs.currencyRate", "1.0");
pref( "extensions.foxtrick.prefs.currencySymbol", "€");
pref( "extensions.foxtrick.prefs.oldCurrencySymbol", "€");
pref( "extensions.foxtrick.prefs.htCurrencyTo", "EUR");
pref( "extensions.foxtrick.prefs.module.CurrencyConverter.enabled", false);
pref( "extensions.foxtrick.prefs.htDateformat", "ddmmyyyy");
pref( "extensions.foxtrick.prefs.htCountry", "Sweden");
pref( "extensions.foxtrick.prefs.htSeasonOffset", 0);
pref( "extensions.foxtrick.prefs.module.HTDateFormat.LocalSaison.enabled", false);
pref( "extensions.foxtrick.prefs.module.ExtendedPlayerDetails.value", 0);
pref( "extensions.foxtrick.prefs.statusbarshow", true);
pref( "extensions.foxtrick.prefs.alertSlider", true);
pref( "extensions.foxtrick.prefs.alertSliderGrowl", false);
pref( "extensions.foxtrick.prefs.alertSound", false);
pref( "extensions.foxtrick.prefs.alertSoundUrl", "chrome://foxtrick/content/resources/sounds/DingLing.wav");
pref( "extensions.foxtrick.prefs.module.FoxtrickAlert.NewMail.enabled", false);
pref( "extensions.foxtrick.prefs.disableOnStage", false );
pref( "extensions.foxtrick.prefs.disableTemporary", false );
pref( "extensions.foxtrick.prefs.copyfeedback", true );
pref( "extensions.foxtrick.prefs.SavePrefs_Prefs", true );
pref( "extensions.foxtrick.prefs.SavePrefs_Notes", true );
pref( "extensions.foxtrick.prefs.matchstat.vnukstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstatstotal", false);
pref( "extensions.foxtrick.prefs.matchstat.ahpoints", true);
pref( "extensions.foxtrick.prefs.matchstat.loddarstats", true);
pref( "extensions.foxtrick.prefs.matchstat.peasostats", true);
pref( "extensions.foxtrick.prefs.matchstat.htitavals", true);
pref( "extensions.foxtrick.prefs.matchstat.gardierstats", true);
pref( "extensions.foxtrick.prefs.module.SeniorTeamShortCuts.value", 0 );
pref( "extensions.foxtrick.prefs.cssSkin.value", "chrome://foxtrick/content/resources/css/mainr.css");
pref( "extensions.foxtrick.prefs.module.SkillColoring.no_skill_links.enabled", false );
pref( "extensions.foxtrick.prefs.module.SkillColoring.skill_number_translated.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.TruncateLongNick.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.CheckDesign.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.SingleHeaderLine.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.SmallHeaderFont.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.ShortPostId.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.TruncateLeagueName.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.ReplaceSupporterStar.enabled", false );
pref( "extensions.foxtrick.prefs.module.CopyPostID.AddCopyIcon.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumTemplates.CustomWidth.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.OpenNewTab.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TeamAtAlltid.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.last_5_ips.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Guestbook.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.SendMessage.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Challenge.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Achievements.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Coach.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TransferHistory.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TeamHistory.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.LastLineup.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.NextMatch.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.AddNextMatch.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.CustomLink.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinksMore.CustomLink.enabled", false );
pref( "extensions.foxtrick.prefs.module.shortcutsstatistics.AddLeft.enabled", true );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Forum_ThreadlistSpace.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamSelectBox.AlsoYouthPlayers.enabled", false );
pref( "extensions.foxtrick.prefs.module.HeaderFix.FixLeft.enabled", true );
pref( "extensions.foxtrick.prefs.module.GuestbookAlltidFlags.HideAnswerToLinks.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_My_Team.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_My_Team.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_width_normal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_width_goal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_non_goal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_my.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.normaltext.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.half_time.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchPlayerColouring.Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchPlayerColouring.Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.HT.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.GM.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.MOD.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.LA.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.CHPP.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.editor.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.foxtrick-dev.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.own.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumStaffMarker.flag.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumTemplates.CustomWidth.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.LoginWelcome.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.LoginSupporters.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.ForumReplyToMe.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.TransferMarket.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Challenges.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Guestbook.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.MailToMe.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.MyHTMessages.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Hover.enabled", false );
pref( "extensions.foxtrick.prefs.module.HTDateFormat.FirstDayOfWeekOffset.enabled", false );
pref( "extensions.foxtrick.prefs.module.NewMail.CustomColor.enabled", false );

	
    	