pref( "extensions.foxtrick.prefs.curVersion", "0.5.0.2");   // update with each release
pref( "extensions.foxtrick.prefs.oldVersion", "0.3.73");   // don't change!! (unless you know what you do). shows changes form that version onwards after new installation
pref( "extensions.foxtrick.prefs.HTURL", "^http:\/\/(stage\.|www\d*\.|www\.new\.){0,1}hattrick\.(org|ws|interia\.pl)" );
pref( "extensions.foxtrick.prefs.htLanguage", "en");
pref( "extensions.foxtrick.prefs.htCurrency", "EUR");
pref( "extensions.foxtrick.prefs.currencyRateTo", "1.0");
pref( "extensions.foxtrick.prefs.currencyCode", "EUR");
pref( "extensions.foxtrick.prefs.currencyRate", "1.0");
pref( "extensions.foxtrick.prefs.currencySymbol", "€");
pref( "extensions.foxtrick.prefs.oldCurrencySymbol", "€");
pref( "extensions.foxtrick.prefs.htCurrencyTo", "EUR");
pref( "extensions.foxtrick.prefs.htDateformat", "ddmmyyyy");
pref( "extensions.foxtrick.prefs.htCountry", "Sweden");
pref( "extensions.foxtrick.prefs.htSeasonOffset", 0);
pref( "extensions.foxtrick.prefs.module.HTDateFormat.LocalSaison.enabled", false);
pref( "extensions.foxtrick.prefs.module.ExtendedPlayerDetails.value", 0);
pref( "extensions.foxtrick.prefs.statusbarshow", true);
pref( "extensions.foxtrick.prefs.statusbarshowreload", false);
pref( "extensions.foxtrick.prefs.alertSlider", true);
pref( "extensions.foxtrick.prefs.alertSliderGrowl", false);
pref( "extensions.foxtrick.prefs.alertSliderDBus", false);
pref( "extensions.foxtrick.prefs.alertSound", false);
pref( "extensions.foxtrick.prefs.alertSoundUrl", "chrome://foxtrick/content/resources/sounds/DingLing.wav");
pref( "extensions.foxtrick.prefs.module.FoxtrickAlert.NewMail.enabled", false);
pref( "extensions.foxtrick.prefs.module.FoxtrickAlert.NewForum.enabled", false);
pref( "extensions.foxtrick.prefs.disableOnStage", false );
pref( "extensions.foxtrick.prefs.disableTemporary", false );
pref( "extensions.foxtrick.prefs.copyfeedback", true );
pref( "extensions.foxtrick.prefs.smallcopyicons", true );
pref( "extensions.foxtrick.prefs.DisplayHTMLDebugOutput", false );
pref( "extensions.foxtrick.prefs.onpageprefs", true );
pref( "extensions.foxtrick.prefs.SavePrefs_Prefs", true );
pref( "extensions.foxtrick.prefs.SavePrefs_Notes", true );
pref( "extensions.foxtrick.prefs.matchstat.vnukstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstatstotal", false);
pref( "extensions.foxtrick.prefs.matchstat.ahpoints", true);
pref( "extensions.foxtrick.prefs.matchstat.loddarstats", true);
pref( "extensions.foxtrick.prefs.matchstat.peasostats", true);
pref( "extensions.foxtrick.prefs.matchstat.htitavals", true);
pref( "extensions.foxtrick.prefs.matchstat.gardierstats", true);
pref( "extensions.foxtrick.prefs.module.SeniorTeamShortCuts.value", 0 );
pref( "extensions.foxtrick.prefs.cssSkin.value", "chrome://foxtrick/content/resources/css/mainr.css");
pref( "extensions.foxtrick.prefs.module.SkillColoring.no_skill_links.enabled", false );
pref( "extensions.foxtrick.prefs.module.SkillColoring.skill_number_translated.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.TruncateLongNick.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.CheckDesign.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.HideOldTime.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.SingleHeaderLine.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.SmallHeaderFont.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.ShortPostId.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.TruncateLeagueName.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumAlterHeaderLine.ReplaceSupporterStar.enabled", false );
pref( "extensions.foxtrick.prefs.module.CopyPostID.AddCopyIcon.enabled", true );
pref( "extensions.foxtrick.prefs.module.ForumTemplates.CustomWidth.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.OpenNewTab.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TeamAtAlltid.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.last_5_ips.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Guestbook.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.SendMessage.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Challenge.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Achievements.enabled", true );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.Coach.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TransferHistory.enabled", true );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.TeamHistory.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.LastLineup.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.NextMatch.enabled", true );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.AddNextMatch.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.CustomLink.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinksMore.CustomLink.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinks.YouthMatches.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamPopupLinksMore.YouthMatches.enabled", false );
pref( "extensions.foxtrick.prefs.module.shortcutsstatistics.AddLeft.enabled", true );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Forum_FoxLink_Headers.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Club_Menu_Teamnames.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Page_Minimum_Height.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Forum_Header_Smallsize.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.MatchOrder_Lineheight.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.RTL_Fixes.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.ForumScrollBarFix.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Forum_ThreadlistSpace.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.League_Table.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Guestbook.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.liveHighlightRed.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.HideFlagsInForumHeader.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.HideLeagueInForumHeader.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Highlight_Staff_On_All_Pages.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.HideUnseenMatchesPanel.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.Forum_Spoiler_reveal.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.MatchReportRatingsFontFix.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.HideAchievementsIcons.enabled", false );
pref( "extensions.foxtrick.prefs.module.FixcssProblems.NoLogo.enabled", false );
pref( "extensions.foxtrick.prefs.module.TeamSelectBox.AlsoYouthPlayers.enabled", false );
pref( "extensions.foxtrick.prefs.module.HeaderFix.FixLeft.enabled", false );
pref( "extensions.foxtrick.prefs.module.GuestbookAlltidFlags.HideAnswerToLinks.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_My_Team.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.Text_Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_My_Team.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.BG_Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_width_normal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_width_goal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_non_goal.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_my.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.border_color_goal_away.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.normaltext.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchReportFormat.half_time.enabled", false );
pref( "extensions.foxtrick.prefs.module.CrossTable.cut_long_teamnames.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchPlayerColouring.Home.enabled", false );
pref( "extensions.foxtrick.prefs.module.MatchPlayerColouring.Away.enabled", false );
pref( "extensions.foxtrick.prefs.module.StaffMarker.HT.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.GM.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.MOD.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.LA.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.CHPP.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.editor.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.foxtrick-dev.enabled", true );
pref( "extensions.foxtrick.prefs.module.StaffMarker.own.enabled", false );
pref( "extensions.foxtrick.prefs.module.StaffMarker.flag.enabled", false );
pref( "extensions.foxtrick.prefs.module.StaffMarker.chpps.enabled", true);
pref( "extensions.foxtrick.prefs.module.ForumTemplates.CustomWidth.enabled", false );
pref( "extensions.foxtrick.prefs.module.TickerColoring.LoginWelcome.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.LoginSupporters.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.ForumReplyToMe.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.TransferMarket.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Challenges.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Guestbook.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.MailToMe.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.MyHTMessages.enabled", true );
pref( "extensions.foxtrick.prefs.module.TickerColoring.Hover.enabled", true );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.LoginWelcome.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.LoginSupporters.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.ForumReplyToMe.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.TransferMarket.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.Challenges.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.Guestbook.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.MailToMe.enabled", false );
pref( "extensions.foxtrick.prefs.module.AlertCustomOff.MyHTMessages.enabled", false );
pref( "extensions.foxtrick.prefs.module.HTDateFormat.FirstDayOfWeekOffset.enabled", false );
pref( "extensions.foxtrick.prefs.module.NewMail.CustomColor.enabled", false );
pref( "extensions.foxtrick.prefs.module.ReadHtPrefs.enabled", true );
pref( "extensions.foxtrick.prefs.module.OnPagePrefs.enabled", true );
pref( "extensions.foxtrick.prefs.module.FoxtrickLineupShortcut.HighlightPlayer.enabled", false );
pref( "extensions.foxtrick.prefs.module.CountryList.HideFlagOntop.enabled", false );
pref( "extensions.foxtrick.prefs.module.YouthSkillTable.CopySkillTable.enabled", true );
pref( "extensions.foxtrick.prefs.module.HighlightBotTeams.enabled", false );
pref( "extensions.foxtrick.prefs.module.ForumYouthIcons.pre.enabled", false);
pref( "extensions.foxtrick.prefs.module.htmsStatistics.Home.enabled", false);
pref( "extensions.foxtrick.prefs.module.htmsStatistics.Draw.enabled", false);
pref( "extensions.foxtrick.prefs.module.htmsStatistics.Away.enabled", false);
pref( "extensions.foxtrick.prefs.module.YouthSkillNotes.OnlyOwnTeam.enabled", true);
pref( "extensions.foxtrick.prefs.module.RapidId.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.AlsoOtherTeams.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.HideSideBarOnTableOpen.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Player.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Age.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.TSI.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Form.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Stamina.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Keeper.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Defending.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Playmaking.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Winger.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Passing.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Scoring.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Set_pieces.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Yellow_card.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Red_card.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Bruised.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Injured.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Speciality.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Last_stars.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.own.Last_position.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Player.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Age.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.TSI.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Form.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Stamina.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Keeper.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Defending.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Playmaking.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Winger.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Passing.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Scoring.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Set_pieces.enabled", false );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Yellow_card.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Red_card.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Bruised.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Injured.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Speciality.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Last_stars.enabled", true );
pref( "extensions.foxtrick.prefs.module.AdultSkillTable.other.Last_position.enabled", true );
