pref( "extensions.foxtrick.prefs.HTURL", "^http:\/\/(stage\.|www\d*\.|www\.new\.){0,1}hattrick\.(org|ws|interia\.pl)" );
pref( "extensions.foxtrick.prefs.htLanguage", "en");
pref( "extensions.foxtrick.prefs.alertSlider", true);
pref( "extensions.foxtrick.prefs.alertSliderGrowl", false);
pref( "extensions.foxtrick.prefs.alertSound", false);
pref( "extensions.foxtrick.prefs.alertSoundUrl", 'chrome://foxtrick/content/resources/sounds/DingLing.wav');
pref( "extensions.foxtrick.prefs.disableOnStage", false );
pref( "extensions.foxtrick.prefs.matchstat.vnukstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstats", true);
pref( "extensions.foxtrick.prefs.matchstat.hatstatstotal", false);
pref( "extensions.foxtrick.prefs.matchstat.ahpoints", true);
pref( "extensions.foxtrick.prefs.matchstat.loddarstats", true);
pref( "extensions.foxtrick.prefs.matchstat.peasostats", true);
pref( "extensions.foxtrick.prefs.matchstat.htitavals", true);
pref( "extensions.foxtrick.prefs.matchstat.gardierstats", true);
